# theme="serika-dark"
# theme="bogster"
# theme="dark_high_contrast"
# theme="ttox"
theme="dy"

[editor]
line-number = "relative"
#bufferline = "multiple"
shell = ["zsh", "-c"]

[keys.normal]
C-g = [":vnew", ":insert-output git diff", ":set-language diff", "move_visual_line_down"]
