# theme="serika-dark"
# theme="bogster"
# theme="dark_high_contrast"
# theme="ttox"
theme="dy"

[editor]
line-number = "relative"
shell = ["zsh", "-c"]

[keys.normal]
C-g = [":vnew", ":insert-output git diff ':!Cargo*'", ":set-language diff", "move_visual_line_down"]

[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"
