theme="dy"

[editor]
color-modes = true
line-number = "relative"
shell = ["zsh", "-c"]

[keys.normal]
C-g = [":vnew", ":insert-output git diff ':!Cargo*'", ":set-language diff", "move_visual_line_down"]
