[[language]]
name = "json"
indent = {tab-width = 4, unit = " "}


[[language]]
name = "python"
roots = ["pyproject.toml", "setup.py", "Poetry.lock", ".git"]
language-servers = ["pylsp"]
auto-format = true
formatter = {command = 'black', args = ["--quiet", "-"]}

[language-server.pylsp.config.pylsp]
configurationSources = ['flake8']

[language-server.pylsp.config.pylsp.plugins]
rope_autoimport = {enabled = true }
flake8 = {enabled = true}
pycodestyle = {enabled = false}
mccabe = {enabled = false}
pyflakes = {enabled = false}
pyls = {enabled = true, live_mode = true}
