inherits = "ttox"

"warning" = { bg = "default", fg = "light-yellow" }
"error" = { bg = "default", fg = "light-red" }
"hint" = { bg = "default", fg = "light-blue" }

"comment" = { bg = "default", fg = "gray" }
"constant" = { bg = "magenta", fg = "black" }
