inherits = "ttox"

"warning" = { bg = "default", fg = "light-yellow" }
"error" = { bg = "default", fg = "light-red" }
"hint" = { bg = "default", fg = "light-blue" }

"comment" = { bg = "default", fg = "gray" }
"constant" = { bg = "light-cyan", fg = "black" }
"string" = { bg = "green", fg = "black" }

"ui.statusline.inactive" = { fg = "black", bg = "gray" }
"ui.statusline.normal" = { fg = "black", bg = "magenta" }
"ui.statusline.insert" = { fg = "black", bg = "yellow" }
"ui.statusline.select" = { fg = "black", bg = "light-cyan" }
